[tox]
env_list =
    uv310
    uv311
    uv312
    uv313
    uv314

[testenv]
base_python = python3
skip_install = true
allowlist_externals = uv
setenv =
    VIRTUAL_ENV =
    UV_PROJECT_ENVIRONMENT = {toxworkdir}/{envname}-uv
commands =
    uv run --python {env:UV_PYTHON} --extra dev pytest {posargs}

[testenv:uv310]
setenv =
    {[testenv]setenv}
    UV_PYTHON = 3.10

[testenv:uv311]
setenv =
    {[testenv]setenv}
    UV_PYTHON = 3.11

[testenv:uv312]
setenv =
    {[testenv]setenv}
    UV_PYTHON = 3.12

[testenv:uv313]
setenv =
    {[testenv]setenv}
    UV_PYTHON = 3.13

[testenv:uv314]
setenv =
    {[testenv]setenv}
    UV_PYTHON = 3.14
